# Generated by Django 6.0.2 on 2026-03-01 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('correct_answers', models.PositiveBigIntegerField(default=0)),
                ('wrong_answers', models.PositiveBigIntegerField(default=0)),
                ('skipped_questions', models.PositiveBigIntegerField(default=0)),
                ('completed_at', models.DateTimeField()),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgressSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveBigIntegerField(default=0)),
                ('total_correct_answers', models.PositiveBigIntegerField(default=0)),
                ('total_wrong_answers', models.PositiveBigIntegerField(default=0)),
                ('total_skipped_questions', models.PositiveBigIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_summaries', to=settings.AUTH_USER_MODEL)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='academics.subtopic')),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='progress_st_student_33f560_idx'), models.Index(fields=['sub_topic'], name='progress_st_sub_top_00225e_idx')],
                'unique_together': {('student', 'sub_topic')},
            },
        ),
    ]
