# Generated by Django 6.0.2 on 2026-04-21 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_sub_image'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentprogresssummary',
            name='progress_st_student_33f560_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprogresssummary',
            name='progress_st_sub_top_00225e_idx',
        ),
        migrations.AddField(
            model_name='studentprogresshistory',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentprogresssummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprogresssummary',
            name='sub_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subtopic'),
        ),
        migrations.AlterField(
            model_name='studentprogresssummary',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogresssummary',
            name='total_correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogresssummary',
            name='total_skipped_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogresssummary',
            name='total_wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
