# Generated by Django 6.0.2 on 2026-04-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_studentprogresssummary_progress_st_student_33f560_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgressHistory',
        ),
    ]
