# Generated by Django 6.0.2 on 2026-04-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
