# Generated by Django 6.0.2 on 2026-03-01 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('total_marks', models.IntegerField(default=0)),
                ('negative_marking_flag', models.BooleanField(default=False)),
                ('negative_marking', models.FloatField(default=0.0)),
                ('time_limit', models.PositiveBigIntegerField(help_text='Time limit in minutes')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('correct_answers', models.PositiveBigIntegerField(default=0)),
                ('wrong_answers', models.PositiveBigIntegerField(default=0)),
                ('skipped_questions', models.PositiveBigIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='academics.subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student'], name='quizzes_qui_student_7b8cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['sub_topic'], name='quizzes_qui_sub_top_868271_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status'], name='quizzes_qui_status_3ebe55_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['quiz_attempt'], name='quizzes_stu_quiz_at_6700a8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question'], name='quizzes_stu_questio_25f96a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('quiz_attempt', 'question')},
        ),
    ]
