# Generated by Django 6.0.2 on 2026-04-21 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_sub_image'),
        ('questions', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentanswer',
            name='quizzes_stu_quiz_at_6700a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentanswer',
            name='quizzes_stu_questio_25f96a_idx',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='negative_marking',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='negative_marking_flag',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_attempts', to='questions.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='time_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='skipped_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='sub_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subtopic'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_limit',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
