# Generated by Django 6.0.2 on 2026-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('quizzes', '0002_remove_studentanswer_quizzes_stu_quiz_at_6700a8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_attempts', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['quiz_attempt'], name='quizzes_stu_quiz_at_6700a8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question'], name='quizzes_stu_questio_25f96a_idx'),
        ),
    ]
