# Generated by Django 6.0.2 on 2026-03-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_name', models.CharField(db_index=True, max_length=100)),
                ('topic_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Main Topic',
                'verbose_name_plural': 'Main Topics',
                'ordering': ['topic_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(db_index=True, max_length=100)),
                ('subject_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('subject_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_topic_name', models.CharField(db_index=True, max_length=100)),
                ('sub_topic_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sub Topic',
                'verbose_name_plural': 'Sub Topics',
                'ordering': ['sub_topic_name'],
            },
        ),
    ]
