# Generated by Django 6.0.2 on 2026-03-01 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintopic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintopic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_topics', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='main_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='academics.maintopic'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_name',), name='unique_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='maintopic',
            constraint=models.UniqueConstraint(fields=('subject', 'topic_name'), name='unique_topic_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('main_topic', 'sub_topic_name'), name='unique_subtopic_per_main_topic'),
        ),
    ]
