# Generated by Django 6.0.2 on 2026-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_images/'),
        ),
    ]
